### ISSUE TITLE
slice threading causes not bitexact output between multithreads and single thread

### ISSUE THREAD

**Issue by richardpl** [sekrit-twc/zimg#104]
Inspecting different outputs reveals some differences by one +1/-1 on some edges?

**Comment by sekrit-twc** [comment]
How are you doing slice threading? With tile_example.cpp?

**Comment by richardpl** [comment]
I'm doing it in C, http://ffmpeg.org/pipermail/ffmpeg-devel/2019-May/244791.html
I set active region among other stuff.
Basically tiles are horizontal slices.

**Comment by richardpl** [comment]
What is strange is that multi-threaded processing produces always same output, does not matter number of tiles/slices set, if it's broken it should be always different.

**Comment by sekrit-twc** [comment]
Please provide an example set of input/output dimensions and active rectangles. From reading the patch, I already see a couple of dubious items.

(1) Active region should only be set on input.  Active region for output implies output to partial region of buffer, which is not supported.
(2) slice_start/slice_end are `int` in `format_init`, but unless you scale by power of two, the window boundaries are fractional.

Tiled operation is tricky to get right. Please consult tile_example.cpp, which I just verified to produce the same output with any tile count, including one mega-tile.

**Comment by richardpl** [comment]
Now I get bitexact output when downscaling. Issue remain with upscaling. (for example 1280x720 to 2560x1440, with tiles of full width and height split in near equal sizes)
Updated patch (with doubles instead of ints)
http://ffmpeg.org/pipermail/ffmpeg-devel/2019-May/244869.html

**Comment by sekrit-twc** [comment]
The remaining difference is because of a difference in order of operation when tiling. The heuristic for determining which axis to sample first is not aware of active region, which causes it to think a (0, 0, 256, 256) => (0, 0, 512, 512) is actually (0, 0, 512, 512) => (0, 0, 512, 512). This is harmless and will be corrected in a future z.lib version.

Independently, I found a performance bug with horizontal slices where slices after the first one will redundantly calculate the previous slices. This will be corrected in a future z.lib version, and in the meantime, vertical slices should be used instead. Vertical slicing is fully validated, since it is what z.lib internally uses for large images.

**Comment by sekrit-twc** [comment]
Also, reviewing your patch, it doesn't look like there is a fallback without slices. Not all graphs can be tiled in z.lib, so you must have a non-sliced fallback.

**Comment by sekrit-twc** [comment]
Fixed in master.
