### ISSUE TITLE
min_luminance option for SDR->HDR mapping

### ISSUE THREAD

**Issue by li-zhi** [sekrit-twc/zimg#144]
zimg provides the `peak_luminance` option to map the peak value of a SDR signal to the linear domain (with a default value of 100.0 nits). I am wondering if it is useful to introduce a similar `min_luminance` option to map the minimum value to the black level, for example, 0.1 nits (I assume it currently uses 0.0 nits?). This will be useful to simulate the characteristics of commercially avaiable SDR displays.

**Comment by sekrit-twc** [comment]
I'm not sure this makes sense. The SDR code value "1" will already map to a luminance much greater than 0, and the Rec.1886 reference standard for interpreting SDR code values is based on a CRT with true black. If the intent is to match the rendering of a LCD display, it would be more appropriate to use a tone-mapping function, but I question the value of encoding this into the HDR signal, when the playback chain will have its own tone-mapping flow.

**Comment by li-zhi** [comment]
If I understand correctly, Rec.1886 defines a EOTF to map the electo signal to the linear luminance of a non-CRT display. It defines several display-specific parameters, including LB - screen luminance for the black and LW - screen luminance for the white. I assume that `peak_luminance` would corresponds to Lw? Similarly, we should have a `min_luminance` corresponding to LB?
![image](https://user-images.githubusercontent.com/17128080/111079301-ac9fcc00-84b6-11eb-8e16-d111f4761d68.png)

**Comment by sekrit-twc** [comment]
Parameters "a" and "b" are meant for calibrating LCD panels. They are not intended for digital manipulation of images. A Rec.709 image may be viewed on any display, which may be a CRT or an LCD of arbitrary brightness. The BT.1886 EOTF parameters "a" and "b" describe how to perform a tone-mapping process from a true-black display (CRT) to a finite-black display (LCD). It would not make sense to apply "a" and "b" in z.lib, because it would tie the image to a specific monitor, and it would also conflict with the calibration process for LCD monitors, which already apply tone-mapping (either sRGB/BT.1886 for SDR or proprietary for HDR).

The peak_luminance parameter in z.lib is unrelated to BT.1886. It exists because there needs to be a convention for anchoring a relative-coded signal (e.g. SDR) to an absolute-coded signal (e.g. ST,2084). There is no problem with mapping 0 to 0, as it round-trips without issue and does not produce black-crush on HDR monitors.

**Comment by li-zhi** [comment]
Hmm. I see what you mean.

Just a quick clarification: if I invoke the following cmd:
```
testapp colorspace --width 384 --height 216 --fullrange-in --fullrange-out --peak-luminance 100 rgbpw@input.plr.rgb rgbpw@output.plr.rgb rgb:709:709 rgb:st_2084:dcip3_d65
```

I assume it first applies some EOTF to map the SDR signal into linear light. Which EOTF has been applied? BT.1886 or sRGB? (I see both implemented in gamma.cpp.)

**Comment by sekrit-twc** [comment]
BT.709 will be decoded using BT.1886 (2..4 pure-power function).

**Comment by ValZapod** [comment]
Yeah, for example my LG C9 has both 2.4 gamma and BT.1886 options for SDR (that is BT.2020 SDR and BT.709 SDR). But because black is 0.00006200 nits on OLED (😁😁, from Dolby Vision block in EDID) 2.4 is alsmost the same as BT.1886. On the other hand it is not that simple: see https://app.spectracal.com/Documents/White%20Papers/BT.1886.pdf

Calman says that it is not 2.4 Gamma precisely. Indeed if we watch netflix it is good enough, as they check for BT.1886 conformance. As of others... Just remember that in Japan anime is done with D93 ambient, not D65. That should be also corrected, etc, etc.
