### ISSUE TITLE
Incorrect conversion to pixel formats RGB24 and RGB48 under some common conditions.

### ISSUE THREAD

**Issue by damster101** [sekrit-twc/zimg#213]
Conversion to RGBS is not affected, even if conversion happens from RGB24 or RGB48. Using high precision YUV as an intermediate seems to be able to mitigate the issue. Also, conversion from RGB48 to RGB24 is interestingly correct (maybe just because the error is quantized away), but the other way around, from RGB24 to RGB48, the conversion is incorrect, although that error is small enough to not survive quantization back to RGB24. Conversion to RGB48 or RGB24 from RGBS is incorrect.
Using error diffusion dither did not mitigate the issue.

This appears to be an issue inherited from swscale.

The error was indiscernible to me on the images I've tried. The error is largest for conversion from RGBS to RGB24.

I used ImageMagick as reference. But the fact that a zimg conversion from RGB24 to RGBS back to RGB24 is lossy, is proof that there is definitely something wrong with zimg:
`ffmpeg -i rgb24.png -vf zscale,format=gbrpf32le,zscale,format=rgb24 distorted.png`
This command will produce an output not pixel-perfect to the input.

**Comment by ValeZAA** [comment]
You must add 'format=gbrp16le' after 'zscale'. Otherwise, FFmpeg instructs z.lib to perform a no-op conversion from YUV to YUV, and instead uses its internal code (swscale) to convert to RGB24.

See https://trac.ffmpeg.org/ticket/8034


>Using high precision YUV as an intermediate seems to be able to mitigate the issue

That phrase makes no sense. 8 bit YCbCr is not enough to preserve RGB24, you need 9.5 bit YCbCr.

What is the mistake when you got from RGB24 to RGB48?

>gbrpf32le

It is quite hard to get float format like that correctly, I do not think ffmpeg does.

**Comment by damster101** [comment]
> You must add 'format=gbrp16le' after 'zscale'. Otherwise, FFmpeg instructs z.lib to perform a no-op conversion from YUV to YUV, and instead uses its internal code (swscale) to convert to RGB24.
> 
> See https://trac.ffmpeg.org/ticket/8034
> 
> > Using high precision YUV as an intermediate seems to be able to mitigate the issue
> 
> That phrase makes no sense. 8 bit YCbCr is not enough to preserve RGB24, you need 9.5 bit YCbCr.
Yes, that's, why I said high precision, I used 16-bit.

> What is the mistake when you got from RGB24 to RGB48?
> 
> > gbrpf32le
> 
> It is quite hard to get float format like that correctly, I do not think ffmpeg does.

1. The output is also incorrect when going directly from RGB24 to RGB48, according to ImageMagick anyway.
2. Does zimg really not support 32-bit float as output, so swscale has to take over in FFmpeg? Why not? That's hard to believe. It definitely supports it as input... And I do not see how it would be hard to get the RGB24 to 32-bit float conversion correct. Actually, I am convinced that the RGB24 to 32-bit float conversion is done with no significant distortion, if any at all, because `ffmpeg -i rgb24.png -vf zscale,format=gbrpf32le,zscale=matrix=1,format=yuv444p16le,zscale,format=rgb24 out.png` produces a pixel-perfect output.

**Comment by ValeZAA** [comment]
>And I do not see how it would be hard to get the RGB24 to 32-bit float conversion correct


Each of those conversions you talk about had or still have bugs in the past, float or integer, matrix or primaries or chroma siting.

Here is this, and author was complaining there is still big error after he fixed it. 

>These are floating points scaled to 16-bit values.
Even with my patch, I'm kinda disturbed how much error there is.

https://patchwork.ffmpeg.org/project/ffmpeg/patch/20200912090714.66582-3-mindmark@gmail.com


I am asking you to give some hex values where the issue is conpared to imagemagick.

**Comment by ValeZAA** [comment]
>The logic of when to use z.lib vs swscale is within FFmpeg. This case is sent to swscale, because the formats are not planar.

Nice, known bug: https://trac.ffmpeg.org/ticket/7978#comment:14

**Comment by damster101** [comment]
Thanks, that is some crucial information.
Sticking to planar formats (gbrp/gbrp16) in FFmpeg indeed solves this. Very nice.
