### ISSUE TITLE
The result of resize.Point is shifted when scaling down

### ISSUE THREAD

**Issue by HolyWu** [sekrit-twc/zimg#46]
Origianl image(1920x1080): http://i.imgur.com/jL5Cqwh.png
Comparison between fmtconv and zimg(scale down to 960x540): http://screenshotcomparison.com/comparison/167402
I also compare AviSynth's internal PointResize and get the same result of fmtconv's.

**Comment by sekrit-twc** [comment]
I tested with the checkerboard below and observe the expected result for the point kernel. The result is a solid color, indicating no drift of the phase, i.e. exactly every other pixel has been selected.

    Interleave(BlankClip(width=540, height=960, color=color_red), BlankClip(width=540, height=960, color=color_green)).AssumeFieldBased().Weave()
    Interleave(TurnLeft(), TurnRight()).AssumeFieldBased().Weave()
    #PointResize(960, 540)

As you know, when scaling by a 0.5 factor and preserving center position, the even and odd source samples are equidistant from the output position. For the point kernel, that means that either phase is a valid, leading to the ambiguous outcome you observed. It turns out that AVS (did not check fmtconv) rounds up (to the bottom-right) the phase when it is exactly halfway between samples, yielding a green image, whereas z.lib rounds down, yielding red.

There is no "correct" way to do this, and you should just not use the point filter to downsample.
