### ISSUE TITLE
Plz update libtool -version-info

### ISSUE THREAD

**Issue by dubhater** [sekrit-twc/zimg#55]
zimg version 2.2.1 still produces libzimg.so.2.0.0.

**Comment by sekrit-twc** [comment]
It is still ABI compatible, so why should the SONAME be changed?

**Comment by dwbuiten** [comment]
Because for ABI compatibility, they can link to `libzimg.so.2` (symlink) since the major version is supposed to convey ABI compatibility info. The reason to bump the minor and patch levels is so that applications can require a certain new version that may add a new function, but keep the ABI stable. E.g. 2.2.0 could add some new function, but keep ABI stability.

**Comment by sekrit-twc** [comment]
Nothing has changed at the ABI level.
