### ISSUE TITLE
Documentation would really be appreciated.

### ISSUE THREAD

**Issue by george84** [sekrit-twc/zimg#74]
This library seems to be used by ffmpeg and vapoursynth. These projects provide little documentation. The documentation, especially for color conversion is missing. The use and relation of parameters matrix, matrixin, primaries, primariesin, transfer, transferin, range, rangein can only be found out by looking at code or hoping to find an example somewhere. It is not clear between which colorspaces a conversion is possible. For example REC.709 to REC.2020 seems impossible. 

I would appreciate if the basic use of this library would be documented in a way that non video specialist, but not complete beginners, could understand it, and if there would be provided examples.

Especially in the domain RGB to HDR10.

**Comment by sekrit-twc** [comment]
For application usage, you should consult the relevant application developer. The library API is fully documented in `zimg.h`. If there is some aspect of the API that is unclear, please feel free to provide further details, so that it can be clarified.

Rec.709 to Rec.2020 is fully supported.

**Comment by kblomster** [comment]
@george84 The numeric range, color matrix, color primaries and transfer function are fundamental color space parameters. The parameter pairs (matrix/matrixin, range/rangein and so on) are there because the source image that you are converting from has one set of parameters (the ones suffixed with "in") while the target image that you are converting to has another set that is potentially different.

If you have trouble figuring out what the parameters actually mean, I suggest you start with some basic theory. [This document](http://www.poynton.com/PDFs/coloureq.pdf) is ancient (1998) but goes over it all relatively concisely and without getting into too much math.

**Comment by sekrit-twc** [comment]
Closing this issue. If you have a specific question, feel free to reopen.
