### ISSUE TITLE
API: Version Number

### ISSUE THREAD

**Issue by msg7086** [sekrit-twc/zimg#8]
Hi,
Thanks for the great tool, and I've ported this into x265 project.

Is it possible to include version information somewhere in the zimh.h?
Not the `ZIMG_API_VERSION 1` but something "true" version, such as MAJOR 1 MINOR 1 MICRO 123 etc. So that when I compile and link against the libz, I know which version I'm using.

**Comment by sekrit-twc** [comment]
Defining the library version as a header macro doesn't make much sense because the actual binary version could be different with dynamic linking. Unfortunately, if I were to add a get_version() API function, it would change the API version, so I can not do this on API v1. I will add this to the list of changes for API v2 instead.

**Comment by msg7086** [comment]
Yes you are right. I was thinking about this when I was compiling on Windows, where I prefer static linking. Feel free to reject this if you don't think it's that necessary ;)

**Comment by sekrit-twc** [comment]
I'm working on finalizing the interface for zlib API v2. Does the following API work for you?

    #define ZIMG_API_VERSION 2

    void zimg2_get_version_info(unsigned *major, unsigned *minor, unsigned *micro);

    unsigned zimg2_get_api_version(void);

**Comment by msg7086** [comment]
Looks good to me. Awesome, thanks.

**Comment by sekrit-twc** [comment]
Included in v2.
